version: '1.0.0'

build:
  name: Sobaka

#extends: ".gobbler/dev-setup.yml"
#
#config:
#  command_prefix: "@"
#
#env_files:
#  - ".env"
#  - ".env.dev"

properties:
  JAVA_HOME_DIR: "C:\\Program Files\\${version}\\Java"
  JAVA_COM: "${PPTY.JAVA_HOME_DIR}/bin/java -jar"
  WIN_PROGRAM_FILES: "C:\\Program Files"
  BASH_CMD_UNIX: "bash -c"
  BASH_CMD_WINDOWS: "${BIN.bash} -c"

# SYSTEM - Current Local Machine
# VM - Installed Vagrant On Your Local Machine
target: SYSTEM

programs:
  docker-bin: "docker exec -it"
  gobbler: "java -jar ./bin/gobbler.jar go"
  bash: "${PPTY.WIN_PROGRAM_FILES}\\Git\\git-cmd.exe"

commands:

  cd-status:
    scripts:
      - 'echo "[CURRENT DIRECTORY STATUS]"'
      - "ls -la"
      - "du -h ."

  health-check:
    description: "Check Health Of All Applications"
    properties:
      JAVA_RUN: "${env.JAVA_HOME}/bin/java ${ARGUMENTS[2]} -jar ${ARGUMENTS[0]}"
    scripts:
      - "${bash} ./healthCheck.sh"

  start-mariadb:
    scripts:
      - "cd-status"
      - "docker-compose up -d dcp-mariadb"
      - "${gobbler.programs.bash} ./healthCheck.sh"

  start-couchbase:
    scripts:
      - "@cd-status"
      - "docker-compose up -d dcp-couchbase-server"
      - "${gobbler.programs.bash} dcp-couchbase-server top -s 10"

  start-databases:
    scripts:
      - "start-mariadb"
      - "start-couchbase"

  start-consul:
    scripts:
      - "docker-compose up -d dcp-consul"

  start-main:
    scripts:
      - "start-consul"
      - "start-databases"